spring:
  datasource:
    url: jdbc:mysql://localhost:6666/wordmem?useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: yls
  expiration: 86400000

logging:
  level:
    com:
      yls:
        word_springboot:
          config: DEBUG